spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel3.cloudtype.app:32084/library
    username: root
    password: root

  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtYXNzaWdubWVudC1kYXRhLXdpdGgtand0LXNlY3JldC1rZXk=

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: dev


  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging.level:
  org.hibernate.SQL: debug
