spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/library
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging.level:
  org.hibernate.SQL: debug
